### ISSUE TITLE
[native] native crash

### ISSUE THREAD

**Issue by nicelyjust** [google-home/sample-app-for-matter-android#87] opened 2023-02-24 09:15 UTC
Reproduction steps
1. A test device([tv-app](https://github.com/project-chip/connectedhomeip/tree/master/examples/tv-app)) was commissioned by GHSAFM
2. stay on the homepage for a while,then it may crash

Version(s)
latest

LOG
[crash.txt](https://github.com/google-home/sample-app-for-matter-android/files/10822476/crash.txt)

**Comment by pierredelisle** [comment] 2023-03-04 02:57
OK, so looks like this may be related to #91.
If someone can provide details on how to reproduce consistently, it will be easier to investigate.

**Comment by pierredelisle** [comment] 2023-03-04 22:20
Have been able to reproduce. Looking into it.

**Comment by pierredelisle** [comment] 2023-03-11 01:46
Should be fixed in PR #98.

**Closed by pierredelisle** 2023-03-11 01:46 UTC
Labels: bug
